version: 0.2

env:
  variables:
    APP_NAME: "step-funcs"
    IMAGE_TAG: $Stage

phases:
    install:
      commands:
        - export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
        - echo $CODEBUILD_GIT_MESSAGE
        - echo $AWS_DEFAULT_REGION
        - export REGION=$AWS_DEFAULT_REGION
        - aws --version

    pre_build:
        commands:
          - ACCOUNT_ID=$(aws sts get-caller-identity|jq -r '.Account')
          - export ACCOUNT_ID=$ACCOUNT_ID
    build:
        commands:
          - echo Build started on `date`
          - pwd
          - cd $CODEBUILD_SRC_DIR/src/offline/movie/step-funcs/
          - echo $Stage
          - ./build.sh $Stage

    post_build:
        commands:
          - echo Build completed on `date`
