# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# list of resource config to be applied
resources:
- ui-deployment.yaml
- ui-service.yaml
- virtual-service.yaml

commonLabels:
  author: mingtong
