version: 0.2

env:
  variables:
    APP_NAME: "step-funcs"
    METHOD: "customize"
#  secrets-manager:
#    GITHUB_USER: gcr-rs-dev-workshop-secret:githubUser
#    ACCESS_TOKEN: gcr-rs-dev-workshop-secret:accessToken
#    APP_CONF_REPO: gcr-rs-dev-workshop-secret:appConfRepo

phases:
    install:
      commands:
        - export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
        - echo $CODEBUILD_GIT_MESSAGE
        - echo $AWS_DEFAULT_REGION
        - export REGION=$AWS_DEFAULT_REGION
        - aws --version

    pre_build:
        commands:
          - ACCOUNT_ID=$(aws sts get-caller-identity|jq -r '.Account')
          - export ACCOUNT_ID=$ACCOUNT_ID
    build:
        commands:
          - echo Build started on `date`
          - pwd
          - cd $CODEBUILD_SRC_DIR/src/offline/news/customize/step-funcs/
          - echo $Stage
          - ./build.sh $Stage $METHOD

    post_build:
        commands:
          - echo Build completed on `date`
